
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# EINSTELLUNGEN
# ============================================================

# Eine oder mehrere XYZ-Trajektorien
FILE_PATHS = [
    Path(
        r"C:\Users\morit\_Uni-FU\Semester 4\Molekueldynamik\md-project-08-group-04\results\2026-07-14_13-23-53\my_simulation_pos.xyz"),
    # Path(r"C:\Pfad\zu\weiterer_trajectory.xyz"),
]

# Die XYZ-Datei enthält offenbar Ångström.
# 1 Å = 0.1 nm
COORDINATE_SCALE_TO_NM = 0.1

# Boxlänge der Simulation in nm
BOX_LENGTH_NM = 6.0

# Gemeinsame Verschiebung des gesamten Systems entfernen
REMOVE_GLOBAL_TRANSLATION = True

# Unvollständigen letzten Frame ignorieren
#
# Das ist hilfreich, wenn die Datei während einer noch laufenden
# Simulation gelesen wird oder ein Dateiausschnitt verwendet wird.
IGNORE_INCOMPLETE_LAST_FRAME = True

# Logarithmische y-Achse
USE_LOG_SCALE = False

# Ausgabeordner
OUTPUT_FOLDER = Path("fluctuation_plots_xyz")

# Name des Diagramms
OUTPUT_FILENAME = "atom_fluctuation_by_index.png"

# Anzahl der Klassen im Fluktuationshistogramm
HISTOGRAM_BINS = 100

# Namen der Ausgabedateien
OUTPUT_FILENAME = "atom_fluctuation_by_index.png"
HISTOGRAM_FILENAME = "atom_fluctuation_histogram.png"

# True:
# Histogramm wird auf die relative Häufigkeit normiert.
#
# False:
# Histogramm zeigt die absolute Anzahl der Teilchen.
NORMALIZE_HISTOGRAM = False


# ============================================================
# XYZ-TRAJEKTORIE EINLESEN
# ============================================================

def load_xyz_trajectory(file_path):
    """
    Liest eine XYZ-Trajektorie mit mehreren Frames ein.

    Erwartetes Format:

        500
        Generated by write_xyz_trajectory
        Ar x y z
        Ar x y z
        ...
        500
        Generated by write_xyz_trajectory
        Ar x y z
        ...

    Rückgabe
    --------
    atom_names:
        Atomsymbole des ersten vollständigen Frames.

    positions:
        Array mit Form:

            (n_frames, n_particles, 3)

        Die Positionen werden direkt in nm umgerechnet.

    comments:
        Kommentarzeilen der vollständigen Frames.
    """

    file_path = Path(file_path)

    if not file_path.exists():
        raise FileNotFoundError(
            f"Datei nicht gefunden:\n{file_path}"
        )

    frames = []
    comments = []

    reference_atom_names = None
    reference_particle_count = None

    with file_path.open(
        mode="r",
        encoding="utf-8"
    ) as xyz_file:

        frame_index = 0

        while True:

            # Leere Zeilen überspringen
            first_line = xyz_file.readline()

            while first_line and not first_line.strip():
                first_line = xyz_file.readline()

            # Reguläres Dateiende
            if not first_line:
                break

            # Erste Zeile eines Frames:
            # Anzahl der Teilchen
            try:
                number_of_particles = int(
                    first_line.strip()
                )

            except ValueError as error:
                raise ValueError(
                    f"Ungültige Teilchenzahl vor Frame "
                    f"{frame_index}:\n"
                    f"{first_line.strip()}"
                ) from error

            if number_of_particles <= 0:
                raise ValueError(
                    f"Ungültige Teilchenzahl in Frame "
                    f"{frame_index}: {number_of_particles}"
                )

            # Alle Frames müssen dieselbe Teilchenzahl besitzen
            if reference_particle_count is None:
                reference_particle_count = number_of_particles

            elif number_of_particles != reference_particle_count:
                raise ValueError(
                    f"Frame {frame_index} besitzt "
                    f"{number_of_particles} Teilchen.\n"
                    f"Erwartet wurden "
                    f"{reference_particle_count} Teilchen."
                )

            # Zweite Zeile:
            # Kommentar
            comment_line = xyz_file.readline()

            if not comment_line:
                if IGNORE_INCOMPLETE_LAST_FRAME:
                    print(
                        f"Warnung: Unvollständiger letzter Frame "
                        f"{frame_index} wurde ignoriert."
                    )
                    break

                raise ValueError(
                    f"Kommentarzeile in Frame "
                    f"{frame_index} fehlt."
                )

            atom_names = []
            frame_positions = []

            frame_complete = True

            for particle_index in range(number_of_particles):

                atom_line = xyz_file.readline()

                if not atom_line:
                    frame_complete = False
                    break

                columns = atom_line.split()

                if len(columns) < 4:
                    frame_complete = False
                    break

                atom_name = columns[0]

                try:
                    x = float(columns[1])
                    y = float(columns[2])
                    z = float(columns[3])

                except ValueError:
                    frame_complete = False
                    break

                atom_names.append(atom_name)

                frame_positions.append(
                    [x, y, z]
                )

            # Unvollständigen letzten Frame behandeln
            if not frame_complete:

                if IGNORE_INCOMPLETE_LAST_FRAME:
                    print(
                        f"Warnung: Unvollständiger letzter Frame "
                        f"{frame_index} wurde ignoriert."
                    )
                    break

                raise ValueError(
                    f"Frame {frame_index} ist unvollständig."
                )

            # Atomreihenfolge überprüfen
            if reference_atom_names is None:
                reference_atom_names = atom_names

            elif atom_names != reference_atom_names:
                raise ValueError(
                    f"Die Atomreihenfolge in Frame "
                    f"{frame_index} stimmt nicht mit dem "
                    f"ersten Frame überein."
                )

            # Ångström -> nm
            frame_positions = (
                np.asarray(
                    frame_positions,
                    dtype=float
                )
                * COORDINATE_SCALE_TO_NM
            )

            frames.append(frame_positions)
            comments.append(comment_line.strip())

            frame_index += 1

    if len(frames) == 0:
        raise ValueError(
            f"{file_path.name} enthält keinen "
            f"vollständigen XYZ-Frame."
        )

    positions = np.stack(
        frames,
        axis=0
    )

    print(
        f"{file_path.name}: "
        f"{positions.shape[0]} vollständige Frames, "
        f"{positions.shape[1]} Teilchen"
    )

    print(
        f"Koordinatenbereich nach Umrechnung: "
        f"{np.min(positions):.4f} bis "
        f"{np.max(positions):.4f} nm"
    )

    return (
        np.asarray(reference_atom_names),
        positions,
        comments
    )


# ============================================================
# PERIODISCHE SPRÜNGE ENTFERNEN
# ============================================================

def unwrap_positions(positions, box_length):
    """
    Entfernt scheinbare Sprünge über die periodischen Boxgrenzen.

    Beispiel bei L = 6 nm:

        5.99 nm -> 0.01 nm

    Die tatsächliche Verschiebung beträgt dann 0.02 nm und
    nicht 5.98 nm.
    """

    if box_length is None:
        return positions.copy()

    if box_length <= 0:
        raise ValueError(
            "BOX_LENGTH_NM muss größer als null sein."
        )

    unwrapped = np.empty_like(
        positions,
        dtype=float
    )

    unwrapped[0] = positions[0]

    # Verschiebung zwischen aufeinanderfolgenden Frames
    displacements = np.diff(
        positions,
        axis=0
    )

    # Minimum-Image-Korrektur
    displacements -= box_length * np.round(
        displacements / box_length
    )

    # Kontinuierliche Positionen rekonstruieren
    unwrapped[1:] = (
        positions[0]
        + np.cumsum(
            displacements,
            axis=0
        )
    )

    return unwrapped


# ============================================================
# GLOBALE TRANSLATION ENTFERNEN
# ============================================================

def remove_global_translation(positions):
    """
    Entfernt die gemeinsame Verschiebung aller Teilchen.

    Bei einem System aus identischen Argonatomen ist der
    geometrische Mittelpunkt gleichzeitig der Schwerpunkt.
    """

    frame_centers = np.mean(
        positions,
        axis=1,
        keepdims=True
    )

    return positions - frame_centers


# ============================================================
# RMS-FLUKTUATION BERECHNEN
# ============================================================

def calculate_atom_fluctuations(
    positions,
    box_length=None,
    remove_translation=True
):
    """
    Berechnet für jedes Teilchen die RMS-Fluktuation:

        RMSF_i =
        sqrt(
            mean_t(
                |r_i(t) - <r_i>|²
            )
        )

    Rückgabe
    --------
    atom_indices:
        Teilchenindizes von 0 bis N-1.

    fluctuations:
        RMS-Fluktuation jedes Teilchens in nm.
    """

    if positions.ndim != 3:
        raise ValueError(
            "positions muss die Form "
            "(n_frames, n_particles, 3) besitzen."
        )

    if positions.shape[0] < 2:
        raise ValueError(
            "Für eine Fluktuationsberechnung werden "
            "mindestens zwei vollständige Frames benötigt."
        )

    # Periodische Boxsprünge korrigieren
    processed_positions = unwrap_positions(
        positions=positions,
        box_length=box_length
    )

    # Gemeinsame Bewegung des Systems entfernen
    if remove_translation:
        processed_positions = remove_global_translation(
            processed_positions
        )

    # Mittlere Position jedes Teilchens
    mean_positions = np.mean(
        processed_positions,
        axis=0
    )

    # Abweichungen von der mittleren Position
    deviations = (
        processed_positions
        - mean_positions[np.newaxis, :, :]
    )

    # Räumliches Abstandsquadrat
    squared_displacements = np.sum(
        deviations**2,
        axis=2
    )

    # RMS-Fluktuation
    fluctuations = np.sqrt(
        np.mean(
            squared_displacements,
            axis=0
        )
    )

    atom_indices = np.arange(
        positions.shape[1]
    )

    return atom_indices, fluctuations


# ============================================================
# DATEI AUSWERTEN
# ============================================================

def analyze_file(file_path):
    """
    Liest eine XYZ-Datei ein und berechnet die Fluktuation
    jedes Teilchens.
    """

    atom_names, positions, comments = load_xyz_trajectory(
        file_path
    )

    atom_indices, fluctuations = calculate_atom_fluctuations(
        positions=positions,
        box_length=BOX_LENGTH_NM,
        remove_translation=REMOVE_GLOBAL_TRANSLATION
    )

    maximum_position = np.argmax(
        fluctuations
    )

    print(
        f"Mittlere RMS-Fluktuation: "
        f"{np.mean(fluctuations):.6f} nm"
    )

    print(
        f"Maximale RMS-Fluktuation: "
        f"{fluctuations[maximum_position]:.6f} nm "
        f"bei Teilchen {atom_indices[maximum_position]}"
    )

    return {
        "name": Path(file_path).stem,
        "atom_index": atom_indices,
        "atom_name": atom_names,
        "fluctuation": fluctuations,
        "number_of_frames": positions.shape[0],
    }


# ============================================================
# CSV-DATEI SPEICHERN
# ============================================================

def save_fluctuation_data(results):
    """
    Speichert Teilchenindex, Atomname und RMS-Fluktuation
    als CSV-Datei.
    """

    output_data = {}

    for result in results:

        name = result["name"]

        output_data[
            f"atom_index_{name}"
        ] = pd.Series(
            result["atom_index"]
        )

        output_data[
            f"atom_name_{name}"
        ] = pd.Series(
            result["atom_name"]
        )

        output_data[
            f"rmsf_nm_{name}"
        ] = pd.Series(
            result["fluctuation"]
        )

    output_df = pd.DataFrame(
        output_data
    )

    output_path = (
        OUTPUT_FOLDER
        / "atom_fluctuations_xyz.csv"
    )

    output_df.to_csv(
        output_path,
        index=False
    )

    print(
        f"Fluktuationsdaten gespeichert:\n"
        f"{output_path.resolve()}"
    )


# ============================================================
# HISTOGRAMM NACH TEILCHENINDEX ERZEUGEN
# ============================================================

def create_fluctuation_plot(results):
    """
    Balkendiagramm:

        x-Achse: Teilchenindex
        y-Achse: RMS-Fluktuation in nm
    """

    plt.figure(
        figsize=(14, 7)
    )

    number_of_files = len(results)

    total_bar_width = 0.8
    bar_width = total_bar_width / number_of_files

    for file_index, result in enumerate(results):

        atom_indices = result["atom_index"]
        fluctuations = result["fluctuation"]

        valid = (
            np.isfinite(atom_indices)
            & np.isfinite(fluctuations)
        )

        if USE_LOG_SCALE:
            valid &= fluctuations > 0

        atom_indices = atom_indices[valid]
        fluctuations = fluctuations[valid]

        offset = (
            file_index
            - (number_of_files - 1) / 2
        ) * bar_width

        plt.bar(
            atom_indices + offset,
            fluctuations,
            width=bar_width,
            alpha=0.8,
            label=result["name"]
        )

    if USE_LOG_SCALE:
        plt.yscale("log")

    plt.xlabel("Teilchenindex")
    plt.ylabel("RMS-Fluktuation / nm")

    plt.title(
        "RMS-Fluktuation der Argonatome"
    )

    plt.grid(
        True,
        axis="y",
        which="both",
        alpha=0.3
    )

    plt.legend()
    plt.tight_layout()

    output_path = (
        OUTPUT_FOLDER
        / OUTPUT_FILENAME
    )

    plt.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight"
    )

    print(
        f"Graph gespeichert:\n"
        f"{output_path.resolve()}"
    )

    plt.show()
    plt.close()


# ============================================================
# HAUPTPROGRAMM
# ============================================================

def main():

    if len(FILE_PATHS) == 0:
        raise ValueError(
            "In FILE_PATHS wurde keine XYZ-Datei eingetragen."
        )

    OUTPUT_FOLDER.mkdir(
        parents=True,
        exist_ok=True
    )

    results = []

    for file_path in FILE_PATHS:

        print()
        print(
            f"Werte XYZ-Datei aus:\n{file_path}"
        )

        result = analyze_file(
            file_path
        )

        results.append(result)

    save_fluctuation_data(
        results
    )

    create_fluctuation_plot(
        results
    )


# ============================================================
# HISTOGRAMM DER FLUKTUATIONSVERTEILUNG
# ============================================================

def create_fluctuation_histogram(results):
    """
    Erzeugt ein echtes Histogramm der RMS-Fluktuationen.

    x-Achse:
        RMS-Fluktuation in nm

    y-Achse:
        Anzahl der Teilchen oder Wahrscheinlichkeitsdichte

    Bei mehreren XYZ-Dateien werden die Histogramme
    transparent übereinander dargestellt.
    """

    plt.figure(
        figsize=(10, 6)
    )

    for result in results:

        fluctuations = np.asarray(
            result["fluctuation"],
            dtype=float
        )

        # Ungültige Werte entfernen
        valid_fluctuations = fluctuations[
            np.isfinite(fluctuations)
        ]

        # Für logarithmische Achsen keine Werte <= 0 verwenden
        if USE_LOG_SCALE:
            valid_fluctuations = valid_fluctuations[
                valid_fluctuations > 0
            ]

        if len(valid_fluctuations) == 0:
            print(
                f"Warnung: Für {result['name']} sind keine "
                f"gültigen Fluktuationswerte vorhanden."
            )
            continue

        plt.hist(
            valid_fluctuations,
            bins=HISTOGRAM_BINS,
            alpha=0.55,
            edgecolor="black",
            density=NORMALIZE_HISTOGRAM,
            label=result["name"]
        )

    if USE_LOG_SCALE:
        plt.xscale("log")

    plt.xlabel("RMS-Fluktuation / nm")

    if NORMALIZE_HISTOGRAM:
        plt.ylabel("Wahrscheinlichkeitsdichte")
    else:
        plt.ylabel("Anzahl der Teilchen")

    plt.title(
        "Verteilung der RMS-Fluktuationen"
    )

    plt.grid(
        True,
        axis="y",
        alpha=0.3
    )

    plt.legend()
    plt.tight_layout()

    output_path = (
        OUTPUT_FOLDER
        / HISTOGRAM_FILENAME
    )

    plt.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight"
    )

    print(
        f"Histogramm gespeichert:\n"
        f"{output_path.resolve()}"
    )

    plt.show()
    plt.close()


def main():

    if len(FILE_PATHS) == 0:
        raise ValueError(
            "In FILE_PATHS wurde keine XYZ-Datei eingetragen."
        )

    OUTPUT_FOLDER.mkdir(
        parents=True,
        exist_ok=True
    )

    results = []

    for file_path in FILE_PATHS:

        print()
        print(
            f"Werte XYZ-Datei aus:\n{file_path}"
        )

        result = analyze_file(
            file_path
        )

        results.append(result)

    # Berechnete Werte als CSV speichern
    save_fluctuation_data(
        results
    )

    # Fluktuation jedes einzelnen Teilchens
    create_fluctuation_plot(
        results
    )

    # Verteilung der Fluktuationen über alle Teilchen
    create_fluctuation_histogram(
        results
    )


if __name__ == "__main__":
    main()